# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('cn', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('first_name', models.CharField(max_length=254)),
                ('uidChanged', models.BooleanField(default=False)),
                ('userPassword', models.CharField(max_length=254)),
                ('shadowExpire', models.IntegerField(null=True)),
                ('roll_number', models.IntegerField(null=True)),
                ('policy', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('accounttype', models.CharField(max_length=254)),
                ('telephoneNumber', models.CharField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
