# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='uid',
        ),
    ]
