# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171127_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
    ]
