# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171128_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forwardedmail',
            field=models.CharField(default='khanepeena', max_length=254),
        ),
    ]
