# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_userprofile_shadowexpire'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shadowExpire',
            field=models.CharField(default='12345', max_length=254),
        ),
    ]
