# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_shadowexpire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shadowExpire',
            field=models.IntegerField(default=12345),
        ),
    ]
