# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20171128_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='shadowExpire',
            new_name='shadowexpire',
        ),
    ]
