# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20171129_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='forwardedmail',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userPassword',
        ),
    ]
